"""Domain layer encapsulating business models and protocols."""

from .models import (
    IngredientItem,
    VisionExtractRequest,
    VisionExtractResponse,
    RecipeCandidate,
    RecipeSynthesizerRequest,
    RequiredIngredient,
    SeasoningRatio,
    CookingStep,
    SynthesizedRecipe,
    TTSGenerationRequest,
    StepAudioInfo,
    TTSGenerationResponse,
)
from .protocols import (
    IVisionAgent,
    IHarvesterAgent,
    ISynthesizerAgent,
    IScriptAgent,
    ITTSAgent,
    IGeminiAdapter,
    ISearchAdapter,
    IYouTubeAdapter,
    ITTSEngineAdapter,
)

__all__ = [
    "IngredientItem",
    "VisionExtractRequest",
    "VisionExtractResponse",
    "RecipeCandidate",
    "RecipeSynthesizerRequest",
    "RequiredIngredient",
    "SeasoningRatio",
    "CookingStep",
    "SynthesizedRecipe",
    "TTSGenerationRequest",
    "StepAudioInfo",
    "TTSGenerationResponse",
    "IVisionAgent",
    "IHarvesterAgent",
    "ISynthesizerAgent",
    "IScriptAgent",
    "ITTSAgent",
    "IGeminiAdapter",
    "ISearchAdapter",
    "IYouTubeAdapter",
    "ITTSEngineAdapter",
]
